### ISSUE TITLE
Request: add scrollbar git diff highlights

### ISSUE THREAD

**Issue by AdriVanHoudt** [emroussel/atomize#12]
I'm not sure what this is called but in Atom one dark theme the scrollbar showed git diff statuses.
Is this something that can be added? I'm really enjoying this theme since the new update broke Atom one dark but this is the one thing I'm missing :P
For example:
![image](https://user-images.githubusercontent.com/2361826/76783564-6421d580-67b2-11ea-906d-79ac941e3c6f.png)
![image](https://user-images.githubusercontent.com/2361826/76783575-6ab04d00-67b2-11ea-9be8-a26da22021be.png)

**Comment by emroussel** [comment]
Hey @AdriVanHoudt! I purposefully hid those in this theme because I couldn't figure out how to differentiate between error/deleted and warning/modified colors. In other places, they both use the same red and yellow colors, and I feel like having both in there could be confusing (and it wouldn't make sense to show stuff that was added without also showing the things that were deleted and modified).

My solution so far has been to have the git colors in the editor gutter (right next to the line numbers), but they don't show up next to the scrollbar so you have to scroll to the right lines to see it.

Would love to hear if you have any ideas on how to represent those distinctively (I can't remember what Atom did or if it even did anything and can't check right now) and am definitely opened to suggestions!

**Comment by AdriVanHoudt** [comment]
Yeah makes sense.
I think that Atom one dark has it so that git stuff is on the right and errors on  the left in the gutter and slightly different color.
(removed line and warnings example)
![image](https://user-images.githubusercontent.com/2361826/77299556-efd4be00-6cec-11ea-9126-1ef5db9cd09d.png)

**Comment by emroussel** [comment]
@AdriVanHoudt sorry for the delay and thanks for sending this screenshot. Turns out VS Code does the same (errors and warnings on one side, git stuff on the other). I am not the biggest fan of showing those markers personally (which I think is why I originally hid them), but this theme should still support that functionality and people can hide them in their settings if they don't want it.

I'll release this under a new version later tonight.

**Comment by AdriVanHoudt** [comment]
I fully follow your statement!
Thanks for adding the support, looking forward to the update ✨
