### ISSUE TITLE
Option for darker background

### ISSUE THREAD

**Issue by timburgan** [emroussel/atomize#22]
Hello 

I love this theme, particularly that Markdown is highlighted well, including quoteblocks, inline-code and block code sections.

Is there an option to make the background a little darker though, for more contrast?

Thanks

**Comment by emroussel** [comment]
Hi @timburgan, thanks for the kind words! I don't necessarily want this theme to be high contrast, but is the concern around contrast because of personal preference or did you find areas that weren't accessible/hard to read because of it?

If it's personal preference, VS Code already allows you to overwrite all of the colors from themes manually via the `workbench.colorCustomizations` setting. You can find [a list of color tokens](https://code.visualstudio.com/api/references/theme-color) as well as a [description of the UI elements](https://code.visualstudio.com/docs/getstarted/userinterface) (to find the right tokens to overwrite) in the VS Code docs. It would look something like this:

```json
{
  "workbench.colorCustomizations": {
    "editor.background": "#000"
  }
}
```

If it's an accessibility issue, I would love to know what specific areas you think might be problematic.

**Comment by timburgan** [comment]
❤️ @emroussel  yeah it's just the background I wish was a little darker so text is easier to read.

I'll look into setting it via the JSON 👍

**Comment by emroussel** [comment]
Great!
