### ISSUE TITLE
Color Inconsistency

### ISSUE THREAD

**Issue by ZorinArch** [emroussel/atomize#23]
Hi, there are differences between this theme and Atom.

## VSCode theme Screenshot
![vscode1](https://user-images.githubusercontent.com/62427713/126896316-0697a5e6-7491-4fd0-8f22-11982bf2fea8.png)

## Atom Original theme Screenshot
![atom1](https://user-images.githubusercontent.com/62427713/126896324-c126f40d-6847-404e-82e7-847c4069ceb1.png)

## Versions used
* VSCode version: 1.58.2
* Theme version: 1.5.5

P.S: for brackets color i use **Rainbow Brackets** extension. you can ignore brackets colors.

**Comment by emroussel** [comment]
Hi @ZorinArch 👋, can you be more specific about what inconsistencies you're referring to in your screenshots and would like changed in this theme? The differences I see are:

1. The font on Atom looks a little thinner, giving the impression that it's dimmed compared to VS Code. What OS are you on? There's a very small difference on mac (see last screenshots below) that I'm not sure where it's coming from, but you can verify that Atomize is using the right colors by inspecting the colors in Atom with Chrome's dev tools and compare with the colors used in this theme – they should all be the same, let me know if you find some that aren't!
2. Syntax highlighting of variables, equal signs, and dots is different. Looks like I was using the `language-babel` package for JS syntax in Atom which colors variables in red like it's done in Atomize (since the syntax grammar of VS Code and Atom is different, I couldn't color things like `document` and `console.log` in teal in Atomize). I am not quite sure why the equal sign and dots are in pink (or white without `language-babel`) but I wonder if it's that's a more recent change.

Atom:
<img width="484" alt="Screen Shot 2021-07-25 at 11 37 34 AM" src="https://user-images.githubusercontent.com/12487270/126904826-7bd1f19f-1f70-4a45-85cd-5f4e9cd6b6df.png">

VS Code:
<img width="474" alt="Screen Shot 2021-07-25 at 11 38 22 AM" src="https://user-images.githubusercontent.com/12487270/126904842-7a9a74e8-ca32-4cb6-a812-2ad25304c452.png">

**Comment by ZorinArch** [comment]
Thank you for response and clarification. i was talking about syntax grammar color. i really like Atom One Dark theme.
Thanks a lot for maintaining this extension.

**Comment by emroussel** [comment]
No problem, I'm going to close this issue but feel free to comment on it again if you have more thoughts about this.
